name: audacity
version: 'git'
summary: Audio software for multi-track recording and editing
description: |
  Audacity. free, open source, cross-platform audio software for multi-track
  recording and editing. http://www.audacityteam.org/

grade: stable
confinement: strict

apps:
  audacity:
    command: desktop-launch alsa-launch $SNAP/usr/bin/audacity
    desktop: usr/share/applications/audacity.desktop
    plugs:
    - desktop
    - desktop-legacy
    - home
    - pulseaudio
    - wayland
    - x11

parts:
  alsa:
    after: [alsa-plugins, alsa-lib]
  alsa-plugins:
    after: [alsa-lib]

  audacity:
    after: [desktop-gtk2, alsa]
    plugin: autotools
    source: https://github.com/audacity/audacity.git
    source-tag: Audacity-2.2.2
    prepare: |
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/audacity.svg|' src/audacity.desktop.in
    configflags:
    - --prefix=/usr
    - --with-ffmpeg
    - --with-lame
    - --with-libflac
    - --with-libid3tag
    - --with-libmad
    - --with-libsbsms
    - --with-libsndfile
    - --with-libsoxr
    - --with-libvamp
    - --with-libvorbis
    - --with-lv2
    - --with-midi
    - --with-portaudio=local
    - --with-portmidi
    - --with-portmixer
    - --with-soundtouch
    - --with-twolame
    build-packages:
    - gettext
    - libavcodec-dev
    - libexpat1-dev
    - libflac-dev
    - libgtk2.0-dev
    - libid3tag0-dev
    - liblv2dynparam1-dev
    - libmad0-dev
    - libmp3lame-dev
    - libportmidi-dev
    - libpulse-dev
    - libsbsms-dev
    - libsndfile1-dev
    - libsoundtouch-dev
    - libsoxr-dev
    - libtwolame-dev
    - libvamp-hostsdk3v5
    - libvorbis-dev
    - libwxbase3.0-dev
    - libwxgtk3.0-dev
    - python
    stage-packages:
    - libavcodec-ffmpeg56
    - libexpat1
    - libflac8
    - libgtk2.0-0
    - libid3tag0
    - liblv2dynparamhost1-1
    - libmad0
    - libmp3lame0
    - libportmidi0
    - libpulse0
    - libsbsms10
    - libsndfile1
    - libsoundtouch1
    - libsoxr0
    - libtwolame0
    - libvorbis0a
    - libvorbisfile3
    - libwxbase3.0-0v5
    - libwxgtk3.0-0v5
    stage:
    - -usr/share/alsa
