name: audacity
adopt-info: audacity
summary: Audio software for multi-track recording and editing
description: |
  Audacity. free, open source, cross-platform audio software for multi-track
  recording and editing. http://www.audacityteam.org/

grade: stable
confinement: strict

apps:
  audacity:
    command: desktop-launch alsa-launch $SNAP/usr/bin/audacity
    desktop: usr/share/applications/audacity.desktop
    plugs:
    - desktop
    - desktop-legacy
    - home
    - pulseaudio
    - wayland
    - x11

parts:
  # specify remote part build order
  alsa:
    after: [alsa-lib, alsa-plugins]
  alsa-lib:
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-alisp
    - --disable-aload
    - --disable-python
    - --disable-rawmidi
    - --disable-static
    - --disable-topology
    - --disable-ucm
    - --enable-symbolic-functions
  alsa-plugins:
    after: [alsa-lib]
    # configflags needed until LP#1766878 is fixed
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --libexec=/usr/lib
    - --libdir=/usr/lib
    - --localstatedir=/var
    - --disable-arcamav
    - --disable-avcodec
    - --disable-jack
    - --disable-mix
    - --disable-oss
    - --disable-usbstream
    - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
    - --disable-static
    - LDFLAGS=-L$SNAPCRAFT_STAGE/usr/lib

  audacity:
    after: [desktop-gtk2, alsa]
    plugin: autotools
    source: https://github.com/audacity/audacity.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "${last_committed_tag}"
      else
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/audacity.svg|' src/audacity.desktop.in
    configflags:
    - --prefix=/usr
    - --with-ffmpeg
    - --with-lame
    - --with-libflac
    - --with-libid3tag
    - --with-libmad
    - --with-libsbsms
    - --with-libsndfile
    - --with-libsoxr
    - --with-libvamp
    - --with-libvorbis
    - --with-lv2
    - --with-midi
    - --with-portaudio=local
    - --with-portmidi
    - --with-portmixer
    - --with-soundtouch
    - --with-twolame
    build-packages:
    - gettext
    - libavcodec-dev
    - libexpat1-dev
    - libflac-dev
    - libgtk2.0-dev
    - libid3tag0-dev
    - liblv2dynparam1-dev
    - libmad0-dev
    - libmp3lame-dev
    - libportmidi-dev
    - libpulse-dev
    - libsbsms-dev
    - libsndfile1-dev
    - libsoundtouch-dev
    - libsoxr-dev
    - libtwolame-dev
    - libvamp-hostsdk3v5
    - libvorbis-dev
    - libwxbase3.0-dev
    - libwxgtk3.0-dev
    - python
    stage-packages:
    - libavcodec-ffmpeg56
    - libexpat1
    - libflac8
    - libgtk2.0-0
    - libid3tag0
    - liblv2dynparamhost1-1
    - libmad0
    - libmp3lame0
    - libportmidi0
    - libpulse0
    - libsbsms10
    - libsndfile1
    - libsoundtouch1
    - libsoxr0
    - libtwolame0
    - libvorbis0a
    - libvorbisfile3
    - libwxbase3.0-0v5
    - libwxgtk3.0-0v5
    stage:
    - -usr/share/alsa
